version: '3.5'

services:
  opengram-front:
    container_name: opengram-front
    image: opengram-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
networks:
  opengram-network:
    external:
      name: custom_opengram